name: ui-tests-check
run-name: ${{ github.actor }} is running the UI tests check for PR ${{ github.event.number }}
on:
  pull_request:
    branches:
      - main
jobs:
#  run-android-ui-tests:
#    runs-on: ubuntu-latest
#    strategy:
#      api-level: [29, 30, 31]
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'adopt'
#
#      - name: Gradle cache
#        uses: gradle/gradle-build-action@v2
#
#      - name: AVD cache
#        uses: actions/cache@v3
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-${{ matrix.api-level }}
#
#      - name: Run Android Emulator and execute tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          target: google_apis
#          force-avd-creation: false
#          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot-save -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          arch: x86_64
#          disk-size: 3G
#          ram-size: 3G
#          heap-size: 1500M
#          profile: 3.4in WQVGA
#          channel: canary
#          cores: 6
#          script:
#            ./gradlew :android:connectedCheck

  run-iOS-ui-tests:
    env:
      WORKING_DIRECTORY: ./ios
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install sourcery
        run: brew install sourcery

      - name: Configure sourcery
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: sourcery --config kaluga.sourcery.yml

      - name: Run podImport
        run: ./gradlew :cucumber:podImport

      - name: Run pod install
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: pod install

      - name: Run iOS UI tests
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: xcodebuild -workspace ios.xcworkspace -scheme ios -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -resultBundlePath TestResults test

      - name: Upload test result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: /TestResults*
