name: ui-tests-check
env:
  PR_NUMBER: ${{ github.event.number }}
  ACTOR: ${{ github.actor }}
run-name: $ACTOR is running the UI tests check for PR $PR_NUMBER
on:
  pull_request:
    branches:
      - main
jobs:
  run-android-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Android UI tests
        run: ./gradlew :android:connectedCheck

  run-iOS-ui-tests:
    env:
      WORKING_DIRECTORY: ./ios
    runs-on: macos-13
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run iOS UI tests
        working-directory: $WORKING_DIRECTORY
        run: xcodebuild \
          -workspace ios.xcworkspace \
          -scheme ios \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=16.0' \
          test

